# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='type',
            field=models.CharField(choices=[('+', 'add'), ('-', 'remove')], default=('+', 'add'), max_length=16),
        ),
    ]
